#!/bin/bash

read -p "Enter your AWS Access Key ID: " -e key_id
read -p "Enter your AWS Secret Access Key: " -e secret_key
read -p "Enter your AWS EC2 Key Filename: " -e key_name

export AWS_ACCESS_KEY_ID=$key_id
export AWS_SECRET_ACCESS_KEY=$secret_key
export AWS_KEY_NAME=$key_name
